Processing pipeline
graphops/qos-oracle-v2 pull request #8
Opened 2024-08-21 03:57 UTC by juanmardefago

2024-09-03 09:56 UTC, i0n requested changes
As a general rule I think it’s best we head towards rust code that compiles without warnings.

2024-09-03 09:56 UTC, i0n commented on oracle/datasource/src/logs.rs
> +    ColumnTrait, ConnectionTrait, Database, DatabaseConnection, EntityTrait, InsertResult,
Unused ConnectionTrait here.

2024-09-03 09:56 UTC, i0n commented on oracle/datasource/src/processing.rs
> +    let log = insert_log(
unused var here.

2024-09-03 09:56 UTC, i0n commented on oracle/datasource/src/processing.rs
> +    let log = insert_log(
Unused var here.

2024-09-03 09:56 UTC, i0n commented on oracle/datasource/src/processing.rs
> +async fn publish_to_ipfs<T: serde::Serialize>(data: &T) -> anyhow::Result<String> {
Unused var here.

2024-09-03 09:56 UTC, i0n commented on oracle/migration/src/m20230416_185838_create_table_client_query_result.rs
>          let db = manager.get_connection();
Unused var here.

2024-09-03 09:56 UTC, i0n commented on oracle/migration/src/m20240723_133527_create_table_indexer_attempts.rs
>          let db = manager.get_connection();
Unused var here.

2024-09-03 09:56 UTC, i0n commented on oracle/src/main.rs
> +use chrono::{DateTime, Utc};
DateTime is unused

2024-09-05 05:05 UTC, juanmardefago commented
> As a general rule I think it’s best we head towards rust code that compiles without warnings.

I agree, I think I forgot to make to do a cleanup after all the trial and error to make it work, but glad you pointed it out!
Will fix this once I'm back on QoS Oracle work

2024-10-15 03:50 UTC, juanmardefago commented
@i0n fixed all warnings you mentioned!

2025-03-31 14:21 UTC, juanmardefago commented
Closed since we are moving to a Clickhouse approach instead

2025-03-31 14:21 UTC, closed without merging